# Generated by Django 3.2 on 2023-06-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_id', models.CharField(max_length=50)),
                ('author_id', models.CharField(max_length=50)),
                ('created_on', models.CharField(max_length=50)),
                ('ended_on', models.CharField(max_length=50)),
            ],
        ),
    ]
