# Generated by Django 4.2.2 on 2023-06-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rareapi', '0002_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='artist_id',
            new_name='author_id',
        ),
    ]
